### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by Josiebonnie** [patrickjane/ut-home#6]
Hi,

For some reason, the app just shows a blank screen when i try to open it, and doesnt do anything past this. Im using a Nexus 7 with 16.04 on it, if this helps at all. Thank you for your time and dedication building the app!

**Comment by patrickjane** [comment]
Did you use the app before? In this case it could be that the stored URL for your home assistant became unreachable, and thus a blank page is shown upon start?

Anyway, a way to force open the settings dialog would be to disable wifi/internet connection before starting the app. Let me know if that helps you out.

**Comment by Josiebonnie** [comment]
For some reason, after turning off the wifi and restarting the device, the
app still stays blank. Thanks for the reply!

**Comment by patrickjane** [comment]
Okay so unfortunately I don't have any 16.04 device at the moment, but I used to develop on my Volla Phone running 16.04 when I last made changes to the app.
I have just now tried the app on my Volla Phone running a fresh install of 20.04 with a new installation of the app. The first thing which comes up after app start is the settings dialog, and when I put a wrong URL for home assistant, I will also get a notification popup stating the host could not be reached. So it does not just purely show a blank page. Plus, the settings dialog remains open.

Since your experience is totally different, I suspect that it has nothing to do with network connectivity, but it seems to be a rather general issue. As I don't have a Nexus 7 and neither a device running 16.04, would it be possible for you to debug the app? You would preferably need a linux PC and install a bunch of tools, but otherwise it would probably be as easy as running 2-3 commands. In case you have never done that, I could navigate you through this process if you would be willing to go for it.

**Comment by Josiebonnie** [comment]
Well, being that this was a pretty new project for me (I didn't have much
stored on the tablet that wasn't backed up prior to downloading the app,
and I kinda wanted to focus the tablet on being a home assistant remote
anyways), I just reset the entire system and started from scratch. That
seemed to have worked; everything's running smoothly now. I appreciate the
help!

**Comment by patrickjane** [comment]
Glad to hear!
